### ISSUE TITLE
Regel fuer Sie/ Du

### ISSUE THREAD

**Issue by ghost** [KA-Advocates/KATranslationCheck#10]
Mir ist aufgefallen, dass oft noch in den alten Uebersetzungen das Wort "Sie" anstatt "du" verwendet wird -auch "Du" groß geschrieben. Wir haben uns auf "du" vor einiger Zeit geeinigt. - Danke

edit: auch "Ihre", "Deine"

**Comment by ulikoehler** [comment]
Gute Idee. Ich finde es sehr wichtig, das zu korrigieren. Diese Regel wird vermutlich extrem viele false positives geben, da es auch andere Verwendungen von "Sie" und "Ihre" gibt (z.B. `Maria zählt Äpfel. Ihre Äpfel sind rot`). Evtl. können wir durch die Großschreibung des ersten Buchstabens viele false positives vermeiden, haben aber auch mehr false negatives.

**Comment by alani1** [comment]
Ja, das ist eine wichtiger Punkt ich habe gestern beim approval in der
plattform sehr viele Strings korrigiert, aber sicher auch ganz viele
übersehen. Könnte man diese Regel eventuell auf die Plattform limitieren ?
D.h. nur auf bestimmte verzeichnisse Anwenden ? Aber auch dann denke ich
dass es noch viele False Positives geben wird. d.h. würde ich eher davon
absehen und auf unsere Armee von Testern setzen, dass wir das dann auf der
Testseite beheben.

**Comment by ulikoehler** [comment]
Man kann dafür sicherlich einen RuleWrapper schreiben, der die Regel für bestimmte Dateinamen / Verzeichnisse ignoriert. Das habe ich sowieso vor. Aber ich gebe dir recht, dass es trotzdem extrem viele false positives geben wird.

**Comment by ulikoehler** [comment]
Die rule ist jetzt online.
