### ISSUE TITLE
Rules for Plattform Terms

### ISSUE THREAD

**Issue by alani1** [KA-Advocates/KATranslationCheck#11]
Can we create rules for the following
- Coach uebersetzt als Trainer anstatt Coach
- Challenge als Herausforderung anstatt Challenge
- Post uebersetzt als Post anstatt Beitrag

**Comment by ulikoehler** [comment]
http://kacheck.localgrid.de/coach-translated-to-trainer-instead-of-coach.html
http://kacheck.localgrid.de/challenge-translated-to-herausforderung-instead-of-challenge.html
http://kacheck.localgrid.de/post-translated-to-post-instead-of-beitrag.html
