### ISSUE TITLE
Integrate KA Lint erros in KATC

### ISSUE THREAD

**Issue by alani1** [KA-Advocates/KATranslationCheck#15]
Hi Uli,

es wäre super wenn wir auch die KA Lint errors in deinem Report zeigen könnten. Dies ist ein CSV File welches KA autoamtisch generiert. e.v. können wir schauen dass dein Server dieses per Email erhält, oder jemand lädt das CSV File irgendwie hoch. Lint errors sind wirkliche errors und keine Warnungen, momentan haben wir mehr als 1000 davon.

Denks du es wäre möglich eine LINT rule einzubauen ? In einem ersten schritt manuell, später ev. automatisch per Mail.

https://groups.google.com/a/khanacademy.org/forum/#!topic/i18n-reports/Fl1FF8rTf2A

**Comment by ulikoehler** [comment]
Ich denke dass das grundsätzlich machbar ist, aber wir können es den Strings nicht zuordnen. Pro file kann ich das zuordnen, aber wir kommen nicht an die String IDs von Crowdin ran, da wir nicht das API verwenden. Daher würde ich ein zusätzliches Template hinzufügen, das die lint errors mit entsprechendem Link pro File anzeigt.

Die Integration ist einigermaßen komplex, da man die CSV-Einträge erstmal den Dateien usw. zuordnen muss und das dann noch in die Statistik integrieren muss. Aktuell ist es am einfachsten, die CSV-Datei manuell zu aktualisieren. Später kann man das evtl. über google groups automatisieren. Ich finde es eine sehr komische Lösung von KA, das auf Google Groups zu posten statt einfach auf einer public URL zu aktualisieren.

**Comment by alani1** [comment]
Hm, schade, aber zuordnung zum File wuerde schon helfen, koennte man die
Lint errors nicht einfach als zusaetzliche Rule hinzufuegen und dann pro
File (de_2_high_priority_content_learn.math.algebra-basics.exercises.pot/)
einfach einen neuen Link ? Das sollte ganz einfach sein, du hast ja die
File ID in der URL. Und ueber json kann man die auf den filenamen mappen.
Ich werde bei KA noch genaueres in Erfahrung bringen. Gewisse der Fehler
kann ich auch gar nicht nachvollziehen. vorlaeufig behalten wir diesen
issue einfach pendent.

**Comment by ulikoehler** [comment]
Ich arbeite jetzt wieder an diesem Bug. Es hat sich herausgestellt, dass man mit dem Python-CSV-Modul auch dieses CSV (mit den Newlines) ganz problemlos auslesen kann.

**Comment by ulikoehler** [comment]
Lint ist jetzt integriert, m.W. gibt es nicht mehr Informationen in den Files als diejenigen die bis jetzt angezeigt werden.

Eine große Zahl der Fehler kann ich auch nicht wirklich nachvollziehen. Weißt du ob der Code, der das lint-File generiert irgendwo auf GitHub zu finden ist?
