### ISSUE TITLE
Zeige neben Page generated auch das Datum des POFileDownloads

### ISSUE THREAD

**Issue by alani1** [KA-Advocates/KATranslationCheck#3]
im Falle von KACheck macht das Datum des letzten downloades mehr Sinn als Page generated, oder stimmen diese ueberein ?

Gruss,
Alain

**Comment by ulikoehler** [comment]
Done. Entweder erstellt Crowdin die ZIPs schlampig oder die sind wirklich 5 Monate alt:

```
drwxrwxr-x   6 uli uli  4096 Feb 26 04:53 de/
```

Ich tippe auf ersteres.

**Comment by alani1** [comment]
Ist dies nicht das datum des verzeichnisses? Schau doch mal ein POFile im
zip an.

**Comment by ulikoehler** [comment]
```
-rw-rw-r-- 1 uli uli 2056559 Feb 26 04:54 learn.math.pre-algebra.exercises-de.po
```

Das Skript schreibt jetzt einfach eine zusätzliche Datei, die den Zeitstempel des Downloads enthält.
