### ISSUE TITLE
FailedConstraint as Error Message

### ISSUE THREAD

**Issue by alani1** [KA-Advocates/KATranslationCheck#4]
Kannst du dir mal Anschauen was der FailedConstraint bedeutet ? Es ist im Text nichts gelb markiert.

http://kacheck.localgrid.de/de_1_high_priority_platform_badges.pot/word-problems-not-translated-to-textaufgaben.html

**Comment by alani1** [comment]
same here:
http://kacheck.localgrid.de/de_2_high_priority_content_learn.math.cc-third-grade-math.videos.pot/word-problems-not-translated-to-textaufgaben.html

**Comment by ulikoehler** [comment]
Das ist eine `TranslationConstraintRule`. Die sagt aus, dass ein bestimmter String _nicht_ wie festgelegt übersetzt wurde. Daher kann man auch nichts im Text markieren, da man nicht weiß wie das ansonsten übersetzt wurde.

Im Vorliegen Fall wurde `world problems` mit `Text-Aufgaben` übersetzt statt mit der üblichen Schreibweise `Textaufgaben`. In Hit 3 beim ersten Link mit `Wort-Probleme`.

**Comment by ulikoehler** [comment]
`Divisionstextaufgaben` macht m.E. Sinn. Ich werde die Regel dementsprechend erweitern.
