### ISSUE TITLE
Value with multiple or mixed commata or dots

### ISSUE THREAD

**Issue by alani1** [KA-Advocates/KATranslationCheck#5]
Diese Rule zeigt definitiv zuviele False positives.

http://kacheck.localgrid.de/de_2_high_priority_content_learn.math.cc-sixth-grade-math.exercises.pot/value-with-multiple-or-mixed-commata-or-dots.html

**Comment by ulikoehler** [comment]
Ist das noch aktuell ? Aktuell zeigt `http://kacheck.localgrid.de/value-with-multiple-or-mixed-commata-or-dots.html` nur 41 hits. Die sind meines Èrachtens auch richtig, d.h. man sollte statt `$127{,}154{,}300$` `$127{\,}154{\,}300$` schreiben, wie im Vademecum angegeben.

**Comment by ghost** [comment]
Ich habe hier heute ein paar uebersetzt, leider nur mit `{\ }`. Habe das total uebersehen, dass da ein `Komma` dazu gehoert. Jedoch ist es nur ein minimaler Unterschied des Abstands. Evtl. neue Regel die `{\ }` anzeigt?

**Comment by ulikoehler** [comment]
@w0lfg Rule sollte jetzt online sein: http://kacheck.localgrid.de/instead-of-inside-number.html

**Comment by ulikoehler** [comment]
Ich habe mir jeden einzelnen Hit der jetzt upgedateten Rule angesehen und kann auf den ersten Blick keinerlei Probleme erkennen. Strings wie `Sammle 1.000.000 Energiepunkte` werden m.E. vollkommen korrekt als Fehler erkannt. Korrekt wäre `Sammle 1{\,}000{\,}000 Energiepunkte`.

Daher schließe ich diesen Issue vorerst, kann ihn aber gerne wieder öffnen falls wieder Probleme auftreten.
