### ISSUE TITLE
Direct Link to Crowdin

### ISSUE THREAD

**Issue by alani1** [KA-Advocates/KATranslationCheck#7]
in den Fehlerreports hat es selbst keinen direkten Link zu Crowdin, nur den im Context. Findet man eventuell in den .pot files auch die Crowdin ID der strings ?

Ein direkter Link mit ID sieht z.b. so aus (nach dem # ist die StringID) :
https://crowdin.com/translate/khanacademy/26336/enus-de#3251701

Ansonsten koennte man den direkt link auch einfach so machen :
https://crowdin.com/translate/khanacademy/26336/enus-de#q=HTMLESCAPEDENGLISHSTRING

Denk Link bitte mit target=_top

**Comment by ulikoehler** [comment]
Ja, ich habe das auch schon gesehen. Gerade bei non-exercise-Translations sind manchmal im Beschreibungstext keine Links enthalten.

In den .pot-Files steht allerdings die Crowdin-ID nicht drin. Beispiel:

```
# Description of video <a href="http://translate.khanacademy.org/math/algebra2/systems_eq_ineq/systems_tutorial_precalc/v/independent-and-dependent-systems">http://translate.khanacademy.org/math/algebra2/systems_eq_ineq/systems_tutorial_precalc/v/independent-and-dependent-systems</a>
# (format: html)
#: intl/datastore:1
msgid " Independent and Dependent Systems"
msgstr " Unabhängige und abhängige Systeme"
```

Ich denke, das liegt daran, das die pot-Files von der KA-Software generiert werden,  bevor sie in Crowdin integriert werden. Crowding schreibt dann wahrscheinlich aus Kompatibilitätsgründen keine zusätzlichen Informationen in die Kontexte schreibt.

Aktuell sehe ich daher keine Möglichkeit, noch zusätzliche Links einzufügen. Vielleicht fällt uns in Zukunft noch was ein, daher lasse ich diesen Issue am besten offen.

**Comment by ulikoehler** [comment]
Jetzt gibt es zumindest links zu den entsprechenden Files.
Das funktioniert aktuell noch nur für die Dateien in Unterverzeichnissen.

**Comment by alani1** [comment]
Habe das schon gesehen, super ! jetzt musst du nur noch den Sourcestring
mit HTMLEscapen und zum Link hinzufügen. Ich habe bemerkt es ist jetzt
schwierig den Text mit der Maus zu Markieren und zu kopieren.

**Comment by ulikoehler** [comment]
Funktioniert jetzt wie gewünscht. Klick einfach auf "Translate on Crowdin".
Er nimmt immer die ersten 100 Zeichen des Strings.

**Comment by ulikoehler** [comment]
Sollte ein Link nicht funktionieren, dann versuch im Crowdin-Suchstring eines oder mehrere Zeichnen zu finden, die durch ein Leerzeichen ersetzt werden müssen, sodass die Suche funktioniert.

**Comment by ulikoehler** [comment]
Man muss anscheinend manchmal noch in die Suchleiste klicken und dann Return drücken, sonst findet Crowdin nichts.
